ebot: 
  image: jamesyale/docker-ebot-csgo
  expose: 
    - "12360:12360"
    - "12361:12361"
  links:
    - "mysql:mysql"
ebotweb: 
  image: jamesyale/docker-ebot-csgo-web
  links: 
    - "mysql:mysql"
    - "ebot:ebot"
  ports: 
    - "8081:80"
mysql: 
  expose:
    - "3306"
    - "3307"
  environment: 
    - MYSQL_DATABASE=ebotv3
    - MYSQL_USER=ebotv3
    - MYSQL_PASSWORD=ebotv3
    - MYSQL_ROOT_PASSWORD=ebotv3
    - MYSQL_PORT=3307
  image: mysql
