ebot: 
  image: jamesyale/docker-ebot-csgo
  links: 
    - mysql:mysql
  ports: 
    - "8080:80"
    - "12360:12360"
mysql: 
  environment: 
    - MYSQL_DATABASE=ebotv3
    - MYSQL_USER=ebotv3
    - MYSQL_PASSWORD=ebotv3
  image: mysql

